"""initiate all tables

Revision ID: e68c6dd31913
Revises: 
Create Date: 2021-03-30 16:56:16.784169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68c6dd31913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dtb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('photo', sa.String(length=256), nullable=True),
    sa.Column('keyword_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('asin_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('acos_active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('amazon_id', sa.String(length=100), nullable=False),
    sa.Column('default_profile', sa.BigInteger(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amazon_id')
    )
    op.create_index(op.f('ix_dtb_user_id'), 'dtb_user', ['id'], unique=False)
    op.create_table('dtb_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('currency_code', sa.String(length=5), nullable=True),
    sa.Column('daily_budget', sa.BigInteger(), nullable=True),
    sa.Column('marketplace_id', sa.String(length=20), nullable=True),
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.Enum('VENDOR', 'SELLER', 'AGENCY', name='accounttype'), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['dtb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dtb_profile_id'), 'dtb_profile', ['id'], unique=False)
    op.create_table('sb_campaign',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ad_format', sa.Enum('PRODUCT_COLLECTION', 'VIDEO', name='adformat'), nullable=False),
    sa.Column('budget_type', sa.Enum('LIFETIME', 'DAILY', name='budgettype'), nullable=False),
    sa.Column('budget', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sb_campaign_id'), 'sb_campaign', ['id'], unique=False)
    op.create_table('sb_keyword_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_status', sa.String(length=20), nullable=False),
    sa.Column('campaign_budget', sa.Numeric(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('keyword_status', sa.String(length=20), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('attributed_sales_14d', sa.Numeric(), nullable=False),
    sa.Column('attributed_conversions_14d', sa.Numeric(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sb_keyword_report_id'), 'sb_keyword_report', ['id'], unique=False)
    op.create_table('sd_campaign',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('tactic', sa.Enum('T00001', 'T00020', 'T00030', 'REMARKETING', name='tactictype'), nullable=False),
    sa.Column('budget_type', sa.Enum('LIFETIME', 'DAILY', name='budgettype'), nullable=False),
    sa.Column('budget', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_campaign_id'), 'sd_campaign', ['id'], unique=False)
    op.create_table('sd_target_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('targeting_expression', sa.String(length=50), nullable=True),
    sa.Column('targeting_text', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('attributed_sales_30d', sa.Numeric(), nullable=False),
    sa.Column('attributed_units_ordered_30d', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_target_report_id'), 'sd_target_report', ['id'], unique=False)
    op.create_table('sp_campaign',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('targeting_type', sa.Enum('MANUAL', 'AUTO', name='targetingtype'), nullable=False),
    sa.Column('dailyBudget', sa.Numeric(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_campaign_id'), 'sp_campaign', ['id'], unique=False)
    op.create_table('sp_keyword_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('attributed_sales_7d', sa.Numeric(), nullable=False),
    sa.Column('attributed_units_ordered_7d', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_keyword_report_id'), 'sp_keyword_report', ['id'], unique=False)
    op.create_table('sp_product_ad_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('asin', sa.String(length=30), nullable=True),
    sa.Column('sku', sa.String(length=30), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_product_ad_report_id'), 'sp_product_ad_report', ['id'], unique=False)
    op.create_table('sp_target_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.BigInteger(), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=False),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('targeting_expression', sa.String(length=50), nullable=True),
    sa.Column('targeting_text', sa.String(length=50), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(), nullable=False),
    sa.Column('attributed_sales_7d', sa.Numeric(), nullable=False),
    sa.Column('attributed_units_ordered_7d', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dtb_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_target_report_id'), 'sp_target_report', ['id'], unique=False)
    op.create_table('sb_ad_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sb_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sb_ad_group_id'), 'sb_ad_group', ['id'], unique=False)
    op.create_table('sd_ad_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_bid', sa.Numeric(), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sd_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_ad_group_id'), 'sd_ad_group', ['id'], unique=False)
    op.create_table('sp_ad_group',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_bid', sa.Numeric(), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_ad_group_id'), 'sp_ad_group', ['id'], unique=False)
    op.create_table('sp_camp_neg_keyword',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.Enum('NEGATIVE_EXACT', 'NEGATIVE_PHRASE', name='negativekeywordmatchtype'), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_camp_neg_keyword_id'), 'sp_camp_neg_keyword', ['id'], unique=False)
    op.create_table('sb_keyword',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', 'PENDING', 'DRAFT', name='keywordstate'), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'PHRASE', 'BROAD', name='keywordmatchtype'), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sb_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sb_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sb_keyword_id'), 'sb_keyword', ['id'], unique=False)
    op.create_table('sb_neg_keyword',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', 'PENDING', 'DRAFT', name='keywordstate'), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.Enum('NEGATIVE_EXACT', 'NEGATIVE_PHRASE', name='negativekeywordmatchtype'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sb_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sb_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sb_neg_keyword_id'), 'sb_neg_keyword', ['id'], unique=False)
    op.create_table('sd_neg_target',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression_type', sa.Enum('MANUAL', 'AUTO', name='expressiontype'), nullable=False),
    sa.Column('expression', sa.String(length=30), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sd_ad_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_neg_target_id'), 'sd_neg_target', ['id'], unique=False)
    op.create_table('sd_product_ad',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asin', sa.String(length=30), nullable=True),
    sa.Column('sku', sa.String(length=30), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sd_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sd_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_product_ad_id'), 'sd_product_ad', ['id'], unique=False)
    op.create_table('sd_target',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression_type', sa.Enum('MANUAL', 'AUTO', name='expressiontype'), nullable=False),
    sa.Column('expression', sa.String(length=30), nullable=True),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sd_ad_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sd_target_id'), 'sd_target', ['id'], unique=False)
    op.create_table('sp_keyword',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT', 'PHRASE', 'BROAD', name='keywordmatchtype'), nullable=False),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sp_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_keyword_id'), 'sp_keyword', ['id'], unique=False)
    op.create_table('sp_neg_keyword',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('keyword_text', sa.String(length=80), nullable=False),
    sa.Column('match_type', sa.Enum('NEGATIVE_EXACT', 'NEGATIVE_PHRASE', name='negativekeywordmatchtype'), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sp_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_neg_keyword_id'), 'sp_neg_keyword', ['id'], unique=False)
    op.create_table('sp_neg_target',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression_type', sa.Enum('MANUAL', 'AUTO', name='expressiontype'), nullable=False),
    sa.Column('expression', sa.String(length=30), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sp_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_neg_target_id'), 'sp_neg_target', ['id'], unique=False)
    op.create_table('sp_product_ad',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asin', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=30), nullable=False),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sp_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_product_ad_id'), 'sp_product_ad', ['id'], unique=False)
    op.create_table('sp_target',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('expression_type', sa.Enum('MANUAL', 'AUTO', name='expressiontype'), nullable=False),
    sa.Column('expression', sa.String(length=30), nullable=True),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('state', sa.Enum('PAUSED', 'ENABLED', 'ARCHIVED', name='state'), nullable=False),
    sa.Column('created_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.Column('ad_group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ad_group_id'], ['sp_ad_group.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['sp_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sp_target_id'), 'sp_target', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sp_target_id'), table_name='sp_target')
    op.drop_table('sp_target')
    op.drop_index(op.f('ix_sp_product_ad_id'), table_name='sp_product_ad')
    op.drop_table('sp_product_ad')
    op.drop_index(op.f('ix_sp_neg_target_id'), table_name='sp_neg_target')
    op.drop_table('sp_neg_target')
    op.drop_index(op.f('ix_sp_neg_keyword_id'), table_name='sp_neg_keyword')
    op.drop_table('sp_neg_keyword')
    op.drop_index(op.f('ix_sp_keyword_id'), table_name='sp_keyword')
    op.drop_table('sp_keyword')
    op.drop_index(op.f('ix_sd_target_id'), table_name='sd_target')
    op.drop_table('sd_target')
    op.drop_index(op.f('ix_sd_product_ad_id'), table_name='sd_product_ad')
    op.drop_table('sd_product_ad')
    op.drop_index(op.f('ix_sd_neg_target_id'), table_name='sd_neg_target')
    op.drop_table('sd_neg_target')
    op.drop_index(op.f('ix_sb_neg_keyword_id'), table_name='sb_neg_keyword')
    op.drop_table('sb_neg_keyword')
    op.drop_index(op.f('ix_sb_keyword_id'), table_name='sb_keyword')
    op.drop_table('sb_keyword')
    op.drop_index(op.f('ix_sp_camp_neg_keyword_id'), table_name='sp_camp_neg_keyword')
    op.drop_table('sp_camp_neg_keyword')
    op.drop_index(op.f('ix_sp_ad_group_id'), table_name='sp_ad_group')
    op.drop_table('sp_ad_group')
    op.drop_index(op.f('ix_sd_ad_group_id'), table_name='sd_ad_group')
    op.drop_table('sd_ad_group')
    op.drop_index(op.f('ix_sb_ad_group_id'), table_name='sb_ad_group')
    op.drop_table('sb_ad_group')
    op.drop_index(op.f('ix_sp_target_report_id'), table_name='sp_target_report')
    op.drop_table('sp_target_report')
    op.drop_index(op.f('ix_sp_product_ad_report_id'), table_name='sp_product_ad_report')
    op.drop_table('sp_product_ad_report')
    op.drop_index(op.f('ix_sp_keyword_report_id'), table_name='sp_keyword_report')
    op.drop_table('sp_keyword_report')
    op.drop_index(op.f('ix_sp_campaign_id'), table_name='sp_campaign')
    op.drop_table('sp_campaign')
    op.drop_index(op.f('ix_sd_target_report_id'), table_name='sd_target_report')
    op.drop_table('sd_target_report')
    op.drop_index(op.f('ix_sd_campaign_id'), table_name='sd_campaign')
    op.drop_table('sd_campaign')
    op.drop_index(op.f('ix_sb_keyword_report_id'), table_name='sb_keyword_report')
    op.drop_table('sb_keyword_report')
    op.drop_index(op.f('ix_sb_campaign_id'), table_name='sb_campaign')
    op.drop_table('sb_campaign')
    op.drop_index(op.f('ix_dtb_profile_id'), table_name='dtb_profile')
    op.drop_table('dtb_profile')
    op.drop_index(op.f('ix_dtb_user_id'), table_name='dtb_user')
    op.drop_table('dtb_user')
    # ### end Alembic commands ###
